plugins {
    id 'com.android.application'
}

android {
    namespace 'za.co.thrive11.app'
    compileSdk 35

    defaultConfig {
        applicationId 'za.co.thrive11.app'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }

    signingConfigs {
        release {
            storeFile file('thrive11-release.jks')
            storePassword project.property('THRIVE11_KEYSTORE_PASSWORD')
            keyAlias 'thrive11'
            keyPassword project.property('THRIVE11_KEY_PASSWORD')
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}
